AWSTemplateFormatVersion: '2010-09-09'
Description: A starter AWS Lambda function.
Resources:
  helloworld:
    Properties:
      CodeUri: s3://test-mdl/dae34bf7e6934ac2773ae2ea5ca6a779
      Description: A starter AWS Lambda function.
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs6.10
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
