AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  GetHtmlFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs6.10
      Description: A starter AWS Lambda function.
      Events:
        GetHtmlApi:
          Type: Api
          Properties: 
            Path: /{proxy+}
            Method: Any
  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - GetHtmlFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetHtmlFunction
      Principal: apigateway.amazonaws.com
